name: Lint / Test
on:
  push:

jobs:
  golangci:
    name: Lint
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'

      - name: golangci-lint
        uses: golangci/golangci-lint-action@537aa1903e5d359d0b27dbc19ddd22c5087f3fbc # v3.2.0
        with:
          version: v1.51.1

  test:
    name: Test
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-go@v3
        with:
          go-version: '1.20'
          cache: true

      - run: go test

      - name: Check git repository clean
        run: git diff --exit-code
