name: Release

on:
  push:
    branches: [main]

jobs:
  release-prepare:
    name: Prepare Release
    runs-on: ubuntu-22.04
    outputs:
      result: ${{ steps.prepare.outputs.result }}
      version: ${{ steps.prepare.outputs.version }}
      changeLog: ${{ steps.prepare.outputs.changeLog }}
    steps:
      - uses: argentumcode/release-action@v0.1.2
        id: prepare
        with:
          action: prepare
          token: ${{ secrets.GITHUB_TOKEN }}
          secret: ${{ secrets.RELEASE_SECRET }}

  release:
    name: Release
    runs-on: ubuntu-22.04
    environment: production
    needs:
      - release-prepare
    if: ${{ needs.release-prepare.outputs.result == 'release' }}
    steps:
      - uses: actions/checkout@v3

      - id: 'auth'
        uses: 'google-github-actions/auth@v1'
        with:
          credentials_json: "${{ secrets.GCP_SERVICE_ACCOUNT_JSON_B64 }}"

      - name: 'Set up Cloud SDK'
        uses: 'google-github-actions/setup-gcloud@v1'

      - name: configure docker
        run: gcloud auth configure-docker asia-northeast1-docker.pkg.dev

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: "1.20"

      - name: Prepare Release
        run: |
          set -eu
          echo "$RELEASE_NOTE" > /tmp/release-notes.txt
          git tag v${{ needs.release-prepare.outputs.version }}
        env:
          RELEASE_NOTE: ${{ needs.release-prepare.outputs.changeLog }}

      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: gcp-iap-auth
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Release
        uses: goreleaser/goreleaser-action@ff11ca24a9b39f2d36796d1fbd7a4e39c182630a # v3.1.0
        with:
          distribution: goreleaser
          version: v1.11.5
          args: release --release-notes /tmp/release-notes.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  release-pull-request:
    name: Create Release Pull Request
    runs-on: ubuntu-22.04
    needs:
      - release-prepare
    if: ${{ needs.release-prepare.outputs.result == 'prepare' }}
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-node@v3
        with:
          node-version: "16"

      - name: Prepare Release Notes
        id: release_notes
        run: |
          set -e
          git config --global user.name 'release-bot'
          git config --global user.email 'release-bot'
          npx standard-version
          TAG="$(git tag --points-at HEAD)"
          echo "version=${TAG:1}" >> $GITHUB_OUTPUT
          git diff HEAD^1 HEAD CHANGELOG.md | egrep -v '^\+\+\+' | grep -e '^\+' | sed -e 's/^\+//g' > /tmp/release-notes.txt

      - name: Create Release Pull Request
        uses: argentumcode/release-action@v0.1.2
        with:
          action: create-pull-request
          token: ${{ secrets.GITHUB_TOKEN }}
          version: ${{ steps.release_notes.outputs.version }}
          changelogFile: /tmp/release-notes.txt
          secret: ${{ secrets.RELEASE_SECRET }}
